BANGPRO/urls.py
from django.contrib import admin
from django.urls import path
from BANGAPP import views
from BANGAPP.views import LoginView
from django.conf import settings
from django.conf.urls.static import static

# LikeListView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('registration/join/', views.join, name="join"),
    path('registration/login/', LoginView.as_view(), name="login"),
    path('home/', views.home, name='home'),
    path('recommend/', views.recommend, name='recommend'),
    path('logout/', views.logout, name="logout"),
    path('detail/theme/<int:theme_pk>', views.detail_theme, name="detail_theme"),
    path('new/themeRev', views.new_themeRev, name="new_themeRev"),
    path('edit/themeRev/<int:themeRev_pk>', views.edit_themeRev, name="edit_themeRev"),
    path('delete/themeRev/<int:themeRev_pk>', views.delete_themeRev, name="delete_themeRev"),
    path('detail/themeRev/<int:themeRev_pk>', views.detail_themeRev, name="detail_themeRev"),
    path('list_themeRev/', views.list_themeRev, name="list_themeRev"),
    path('list_themeRevAll/', views.list_themeRevAll, name="list_themeRevAll"),
    path('like/', views.like, name="like"),
    path('hate/', views.hate, name="hate"),
    path('themelike/', views.themelike, name="themelike"),
    path('selectImg/', views.selectImg, name="selectImg"),
    path('mypage/', views.mypage, name="mypage"),
    path('detail/themeRev/themeRevAdd/<int:theme_pk>', views.detail_themeRevAdd, name="detail_themeRevAdd"),
    path('detail/themeRev/themeRevAdd/<int:theme_pk>/<int:review_pk>', views.detail_themeRevAddDetail, name="detail_themeRevAddDetail"),
    path('mypage/mylike/', views.mylike, name="mylike"),
    path('mypage/myreview/', views.myreview, name="myreview"),
    path('detail/shop/<int:shop_pk>', views.detail_shop, name="detail_shop"),
    path('edit_profile/', views.edit_profile, name="edit_profile"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # path('new/themeRevTest', views.new_themeRevTest, name="new_themeRevTest"),

BANGAPP/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from datetime import datetime    

# Create your models here.

class User(models.Model):
    userID = models.CharField(primary_key=True, max_length=128, unique=True)
    userPW = models.CharField(max_length=128)
    userName = models.CharField(max_length=64)
    usersSubname = models.CharField(max_length=64)
    userBirthday = models.DateField()
    userGender = models.IntegerField(default=0)
    ShopRevID = models.IntegerField(default=0)
    ThRevID = models.IntegerField(default=0)
    userImage = models.ImageField(upload_to='userImages/', height_field=None, width_field=None,blank=True, default='userImages/plus.png')    

    def __str__(self):
        return self.userID


class Shoprev(models.Model):
    shoprevID = models.AutoField(primary_key=True, unique=True)
    shoprevTitle = models.CharField(max_length=200)
    shopRating = models.IntegerField(default=0)
    shoprevCont = models.TextField()
    shoprevImage = models.ImageField(upload_to='shopImages', height_field=None, width_field=None,blank=True)
    shoprevDate = models.DateField()
    shoprevWDate = models.DateField(auto_now=True)
    shopID = models.ForeignKey("Shop", related_name="ShopID", on_delete=models.CASCADE, db_column='shopID')
    recom = models.IntegerField(default=0)
    nrecom = models.IntegerField(default=0)
    WriterID = models.ForeignKey("User", related_name="UserID", on_delete=models.CASCADE, db_column='WriterID')

    def __str__(self):
        return self.shoprevTitle


class Shop(models.Model):
    shopID = models.AutoField(primary_key=True, unique=True)
    shopName = models.CharField(max_length=200)
    Location = models.TextField()
    OpenTime = models.TextField()
    Rating = models.IntegerField(default=0)
    PhoneNum = models.CharField(max_length=200)
    Price = models.IntegerField(default=0)
    PageLink = models.TextField()
    ShopIntro = models.TextField()
    shopImage = models.ImageField(upload_to='shopImages/', height_field=None, width_field=None,blank=True)    

    def __str__(self):
      return self.shopName


class ThemeRev(models.Model):
    themeRevID = models.AutoField(primary_key=True)
    themeRevContent = models.TextField()
    themeRevDate = models.DateField()
    themeRevWriteDate = models.DateTimeField(default=datetime.now(), blank=True)
    themeRev_WriterID = models.ForeignKey("User", related_name="themeRev_WriterID", on_delete=models.DO_NOTHING, db_column="themeRev_WriterID", blank=True)
    theme_ID = models.ForeignKey("Theme", related_name="theme_ID", on_delete=models.CASCADE, db_column="theme_id")
    shop_ID = models.ForeignKey("Shop", related_name="shop_ID", on_delete=models.CASCADE, db_column="shop_id")
    themeRevRecom = models.IntegerField(default=0, blank=True)
    themeRevNRecom = models.IntegerField(default=0, blank=True)
    themeRevRating = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])


class Theme(models.Model):
    themeID = models.AutoField(primary_key=True, unique=True)
    themeName = models.CharField(max_length=128)
    themeTimeLimit = models.CharField(max_length=64)
    themeRating = models.IntegerField(default=0)
    themeDifficulty = models.IntegerField(default=0)
    themeHorror = models.IntegerField(default=0)
    themeActivity = models.IntegerField(default=0)
    themeRecomPeople = models.IntegerField()
    ShopID = models.ForeignKey("Shop", related_name="ShopId", on_delete=models.CASCADE, db_column="ShopID", default=1)
    themeGenre = models.CharField(max_length=64)
    themeImage = models.ImageField(upload_to='themeImages/', height_field=None, width_field=None,blank=True)    
    themeIntro = models.TextField(null=True)
    themeLike = models.IntegerField(default=0, blank=True)
    themePrice = models.IntegerField(default=0, blank=True)

    def __str__(self):
      return self.themeName


class Like(models.Model):
    user = models.ForeignKey('User', on_delete=models.CASCADE, related_name="like_record")
    article = models.ForeignKey('ThemeRev', on_delete=models.CASCADE, related_name="like_record")
    
    class Meta:
        unique_together = ('user','article')

class Hate(models.Model):
    user = models.ForeignKey('User', on_delete=models.CASCADE, related_name="hate_record")
    article = models.ForeignKey('ThemeRev', on_delete=models.CASCADE, related_name="hate_record")
    
    class Meta:
        unique_together = ('user','article')


class ThemeLike(models.Model):
    user = models.ForeignKey('User', on_delete=models.CASCADE, related_name="themelike_record")
    liketheme = models.ForeignKey('Theme', on_delete=models.CASCADE, related_name="themelike_record")
    
    class Meta:
        unique_together = ('user','liketheme')


class Test(models.Model):
    grade = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(5)])
    con = models.TextField(null=True)
    Date = models.DateField(null=True)
    themeRevRecom = models.IntegerField(default=0, blank=True)
    themeRevNRecom = models.IntegerField(default=0, blank=True)
    theme_ID2 = models.ForeignKey("Theme", related_name="test1", on_delete=models.CASCADE, db_column="test1", default=1)
    shop_ID2 = models.ForeignKey("Shop", related_name="test2", on_delete=models.CASCADE, db_column="test2", default=1)
    WriterID2 = models.ForeignKey("User", related_name="test3", on_delete=models.CASCADE, db_column="test3", null=True, blank=True)

    

BANGAPP/views.py
from django.contrib import auth
from django.contrib.auth import authenticate
from django.http.response import JsonResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.models import User
from .models import User, Shop, Theme, ThemeRev, Like, Hate, ThemeLike
import json
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
#for loginview
from .forms import LoginForm, ThemeRevForm, TestForm
from django.views import generic
from argon2 import PasswordHasher, exceptions
#for likeview
from django.utils.decorators import method_decorator
from .decorator import login_required
from django.urls import reverse, reverse_lazy
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import FormView, View, RedirectView #Generic View 개발 속도를 빠르게 만들어줌
from django.views.decorators.csrf import csrf_exempt
#for sort 
from django.core.paginator import Paginator
from datetime import datetime
from django.db.models import Count

# Create your views here.
def join(request):
    if request.method == 'GET':
        return render(request, 'registration/join.html')
    elif request.method == 'POST':
        userID = request.POST.get('userID', '')
        userPW = request.POST.get('userPW1', '')
        userName = request.POST.get('userName', '')
        usersSubname = request.POST.get('usersSubname', '')
        userBirthday =request.POST.get('userBirthday', '')
        userGender = request.POST.get('userGender')

        if (userID or userPW or userName or usersSubname or userBirthday or userGender) == '':
            return render(request,'registration/join.html')
        elif request.POST['userPW1'] != request.POST['userPW2']:
            return render(request,'registration/join.html')
        else:
            user = User(
              userID = userID,
              userPW = PasswordHasher().hash(userPW),
              userName = userName,
              usersSubname = usersSubname,
              userBirthday = userBirthday,
              userGender = userGender
          )
            user.save()
        return render(request, 'registration/complete.html', {'user':user})


class LoginView(generic.View): 
  template_name = 'registration/login.html'
  form_class = LoginForm
  success_url = reverse_lazy("home") 
  #Class-level 속성을 가지는 객체들은 import 될 때 배치되는데 URL-seolving 규칙은 import 시간에 세팅되어있지 않아 class 내에서 reverse()를 사용하면 URLconf의 규칙을 인식하지 못한다.

  loginform = LoginForm()
  context = { 'forms' : loginform }

  def post(self, request):
      loginform = LoginForm(request.POST)
      context = { 'forms' : loginform }
      if loginform.is_valid():
          self.request.session['user'] = loginform.cleaned_data['userID']
          # username = self.request.session['user']
          # return super().form_valid(form)
          # return render(request, 'home.html')
          return redirect('home')

      else:
          context['forms'] = loginform
          if loginform.errors:
            for value in loginform.errors.values():
                context['error'] = value
      return render(request, 'registration/login.html', context)

  def get(self,request):
      return render(request, 'registration/login.html', context=self.context)


def logout(request):
    if 'user' in request.session:
        del(request.session['user'])
    return redirect('home')


def mypage(request):
    username = request.session.get('user')
    if User.objects.filter(userID = username).exists():
      user = get_object_or_404(User, userID = username)

      if request.method == "GET":
          # test = request.FILES["imgfile"]
          # print(test)
          # form = user.update(
          #   img = request.FILES["imgfile"],
          # )
          # form.save()
        content = {'user' : user}
        return render(request, 'registration/mypage.html', content)
    return redirect('login')

    
def home(request):
    ordering_priority = []
    sort = request.GET.get('sort')
    ordering_priority.append(sort)
    theme_list = Theme.objects.all()
    themerev = ThemeRev.objects.all()
    shop_list = Shop.objects.all()
    # test = Theme.objects.filter(ShopID_id=shop_list.shopName)
    # print(test)
    # count = test1.aggregate(count=Count('theme_ID'))
    # print(count, test1.count())
    # 테마에 속한 리뷰들의 개수를 불러옴 / 그 개수가 많은 순서대로 정렬
    # theme_list = Theme.objects.all().order_by(*ordering_priority)

    shopscount = shop_list.count()
    themescount = theme_list.count()
    allcount = shopscount + themescount

    q = request.GET.get('q','')
    t = request.GET.get('t', '')
    sort = request.GET.get('sort','')
    if t :
      theme_list = theme_list.filter(ShopID__shopName__icontains=t)
      shop_list = shop_list.filter(shopName__icontains=t)
      allcount = theme_list.count() + shop_list.count()
    if q :
      theme_list = theme_list.filter(themeName__icontains=q)
      shop_list = shop_list.filter(shopName__icontains=q)
      allcount = theme_list.count() + shop_list.count()
    if sort :
      theme_list = theme_list.order_by(sort)
    content = {'shop_list' : shop_list, 'theme_list' : theme_list, 'allcount' : allcount, 'q' : q, 'themerev' : themerev}
    return render(request, 'home.html', content)


def detail_shop(request, shop_pk):
      shop = Shop.objects.get(pk=shop_pk)
      themes = Theme.objects.filter(ShopID=shop_pk)
      review = ThemeRev.objects.filter(theme_ID=shop_pk)
      topreview = review.order_by('-themeRevRecom').first()

      return render(request,'detail_shop.html', {'shop':shop, 'themes':themes, 'review':review, 'topreview':topreview})


def detail_theme(request, theme_pk):
  #이 페이지에서 새로 뭘 작성할게 아니면 아래 두줄은 삭제
    if request.method == "POST":
      return redirect('detail_theme', theme_pk)
    theme = Theme.objects.get(pk=theme_pk)
    review = ThemeRev.objects.filter(theme_ID=theme_pk)
    topreview = review.order_by('-themeRevRecom').first()
    shop = Shop.objects.get(shopID=theme.ShopID.pk)
    # like = Like.objects.filter(article__in=review)
    return render(request, 'detail_theme.html', {'theme':theme, 'review':review, 'topreview':topreview, 'shop':shop})
    

def detail_themeRevAdd(request, theme_pk):
  theme = Theme.objects.get(pk=theme_pk)
  reviews = ThemeRev.objects.filter(theme_ID=theme_pk)
  shop = Shop.objects.get(shopID=theme.ShopID.pk)
  return render(request, 'detail_themeRevAdd.html', {'theme':theme ,'reviews': reviews, 'shop':shop})


def detail_themeRevAddDetail(request, theme_pk, review_pk):
  theme = Theme.objects.get(pk=theme_pk)
  review = ThemeRev.objects.get(pk=review_pk)
  shop = Shop.objects.get(shopID=theme.ShopID.pk)
  writer = User.objects.get(userID=review.themeRev_WriterID)
  username = request.session.get('user')
  context = {'theme':theme, 'review':review, 'shop':shop, 'writer':writer, 'username':username}
  return render(request, 'detail_themeRevAddDetail.html', context)


# 테스트용뷰
# def new_themeRevTest(request):
#   username = request.session.get('user')
#   user = get_object_or_404(User, userID = username)
#   if request.method == "POST":
#     form = TestForm(request.POST)

#     if form.is_valid():
#       print(form.cleaned_data)
#       post = form.save()
#       post.WriterID2 = user
#       post.save()
#       return redirect("new_themeRevTest")
#     else:
#       print('no')
#   else:
#       form = TestForm()
#   context = {'form':form}
#   return render(request, "new_themeRevTest.html", context)


@csrf_exempt
def selectImg(request):
    pk = request.POST.get('pk', None)
    # username = request.session.get('user')
    # user = get_object_or_404(User, userID = username)
    selectTheme = get_object_or_404(Theme, pk=pk)
    themeImg = selectTheme.themeImage
    return HttpResponse(json.dumps(str(themeImg)), content_type="application/json")


def new_themeRev(request):
  username = request.session.get('user')
  # user = get_object_or_404(User, userID = username)
  
  if request.method == "GET":
    if User.objects.filter(userID = username).exists():
      form = ThemeRevForm()
      context = {'form':form,}
      return render(request, "new_themeRev.html", context)
    else:
      # return render(request, './registration.login.html')
      return redirect('login')

  elif request.method == "POST":
    form = ThemeRevForm(request.POST)
    user = get_object_or_404(User, userID = username)

    if form.is_valid():
      print(form.cleaned_data)
      post = form.save(commit=False) #DB save를 지연시켜 중복 save 방지
      post.themeRevWriteDate = datetime.now()
      post.themeRev_WriterID = user
      post.save()
      pk = post.pk
      # return render(request, "new_themeRevCom.html")
      return redirect("detail_themeRev", pk)
    else:
      messages.error(request, 'Error!')
      print('no')
      # post.ip = request.META['REMOTE_ADDR']
  context = {'form':form,}
  return render(request, "new_themeRev.html", context)


def edit_themeRev(request, themeRev_pk):
    username = request.session.get('user')
    user = get_object_or_404(User, userID = username)
    themeRev = get_object_or_404(ThemeRev, pk = themeRev_pk)
    # if themeRev.themeRev_WriterID == user.userID:
    # path-converter로 받은 pk로 수정하려는 post객체를 get

    if request.method == "GET":
      form = ThemeRevForm(instance = themeRev)

    elif request.method == "POST":
        form = ThemeRevForm(request.POST, instance=themeRev)
        # ThemeRevForm의 인스턴스가 themeRev임을 표시
        if form.is_valid():
          print(form.cleaned_data)
          post = form.save(commit=False) #DB save를 지연시켜 중복 save 방지
          post.themeRev_WriterID = user
          post.save()

BANGAPP/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Material+Icons+Outlined" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/gh/moonspam/NanumSquare@1.0/nanumsquare.css">
  <link href="{% static 'css/base.css' %}" rel="stylesheet" type="text/css">
  {% comment %} For Start Rating {% endcomment %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  {% comment %} <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js"></script>  {% endcomment %}
  {% block header %}
  {% endblock header %}
  {% block css %}
  {% endblock css %}
  <title>search</title>
</head>
<body>
  <div class="wrap">
    <div class="nav-bar">
      <div class="nav-title">
        <strong>방탈출 예약 시스템</strong>
      </div>
      <div class="nav-menu">
        <a class="nav-search" href="{% url 'home' %}">검색</a>
        <a class="nav-recommend" href="{% url 'recommend' %}">추천</a>
        <a class="nav-review" href="{% url 'list_themeRev' %}">리뷰</a>
        <a class="nav-mypage" href="{% url 'mypage' %}">마이페이지</a>
      </div>
    </div>
    {% block content %}
    {% endblock content %}
  </div>
  {% block js %}
  {% endblock js%}
</body>
</html>

BANGAPP/templates/edit_themeRev.html
{% extends './base.html' %}
{% load static %}
{% block css %}
  <link href={% static 'css/new_themeRev.css' %} rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="{% static 'widgets/rateit/rateit.css' %}">
{% endblock css %}
{% block content %}
  <div class="content">
    <form action="" method="post">
      {% csrf_token %}
        <div class="submit">
          <h2>리뷰 작성</h2>
          <button type="submit" class="write">작성 완료</button>
          {% comment %} <input type="submit" value="제출 완료"> {% endcomment %}
        </div>
    
    {% comment %} 별점 선택하면 숫자로 환산해서 themeRevRating에 반영 {% endcomment %}
    <div class="star-review box">
      <div class="boxTitle text-top">별점 리뷰</div>
      <input type="range" name="themeRevRating" value="5" required="" id="id_grade" min="0" max="5" step="1" style="display:none;">
      <div id="star_id_grade" class="rateit rateit-bg" data-rateit-backingfld="#id_grade" data-rateit-mode="font" style="font-size:2vw;">
      </div>    
    </div>

    {% comment %} 테마 선택해서 이미지 불러오기 {% endcomment %}
    <div class="visited-theme box">
      <div class="boxTitle text-middle">방문한 방탈출 테마</div>
      <div class="themeImg"></div>
      <div class ="theme-info">
        <div class="fieldWrapper">
          <label for="themeid">테마명:</label>
          {{form.theme_ID}}
        </div>
        <div class="fieldWrapper">
          <label for="shopid">지점명:</label>
          {{form.shop_ID}}
        </div>
        <div class="fieldWrapper">
          <label for="date">방문날짜:</label>
          {{form.themeRevDate}}
        </div>
      </div>
    </div>

    <div class="text-review box">
      <div class="boxTitle text-bottom">텍스트 리뷰</div>
      {{form.themeRevContent}}
    </div>
  </form>
  </div> 

{% endblock content %}
{% block js %}
<script src="{% static 'widgets/rateit/jquery.rateit.min.js' %}" ></script>
<script src="{% static 'widgets/rateit/jquery.rateit.js' %}" ></script>
<script type="text/javascript" src="/static/js/new_themeRev.js"></script>
<script>
  $('#star_id_grade').click(function(){
    star = $('#star_id_grade').rateit('value')
    $('#id_grade').text(star)
    $('#id_grade').val(star)
    test = $('#id_grade')
    console.log(test.val())
  });
  
  </script>
{% endblock js %}

BANGAPP/templates/list_themeRevAll.html
{% extends './base.html' %}
{% load static %}
{% block css %}
<link href={% static 'css/list_themeRevAll.css' %} rel="stylesheet" type="text/css">
<title>review all</title>
{% endblock css %}
{% block content %}
  <div class="content">
    <h2>리뷰 목록</h2>

    <div class="themeRev">
      {% for review in reviews %}
      <a href="{% url 'detail_themeRev' review.pk%}">
      <div class="review-box">
        <div class="summary-cont">{{review.themeRevContent}}</div>
        <div class="summary-bottom">
          <div class="like-count" id="count-{{ review.pk }}">
            ♡{{ review.themeRevRecom }}+</p>
            {% comment %} 이미지 삽입 오류 수정되면 하트 이미지로 대체 {% endcomment %}
          </div>
          <div>
          <input type="button" class="like" name="{{ review.pk }}" value="추천">
          </div>
          <div>
          <input type="button" class="hate" name="{{ review.pk }}" value="비추천">
        </div>        
      </div>
    </div>
      </a>
      {% endfor %}
  <div>
{% endblock content %}
{% block js %}
<script type="text/javascript" src="/static/js/like.js"></script>
<script type="text/javascript" src="/static/js/hate.js"></script>
{% endblock js %}

BANGAPP/templates/new_themeRev.html
{% extends './base.html' %}
{% load static %}
{% block css %}
  <link href={% static 'css/new_themeRev.css' %} rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="{% static 'widgets/rateit/rateit.css' %}">
  <title>new review</title>
{% endblock css %}
{% block content %}
  <div class="content">
    <form action="" method="post">
      {% csrf_token %}
        <div class="submit">
          <h2>리뷰 작성</h2>
          <button type="submit" class="write">작성 완료</button>
        </div>
    
    {% comment %} 별점 선택하면 숫자로 환산해서 themeRevRating에 반영 {% endcomment %}
    <div class="star-review box">
      <div class="boxTitle text-top">별점 리뷰</div>
      <input type="range" name="themeRevRating" value="5" required="" id="id_grade" min="0" max="5" step="1" style="display:none;">
      <div id="star_id_grade" class="rateit rateit-bg" data-rateit-backingfld="#id_grade" data-rateit-mode="font" style="font-size:3vw">
      </div>
    </div>

    {% comment %} 테마 선택해서 이미지 불러오기 {% endcomment %}
    <div class="visited-theme box">
      <div class="boxTitle text-middle">방문한 방탈출 테마</div>
      <div class="themeImg"></div>
      <div class ="theme-info">
        <div class="fieldWrapper">
          <label for="themeid">테마명:</label>
          {{form.theme_ID}}
        </div>
        <div class="fieldWrapper">
          <label for="shopid">지점명:</label>
          {{form.shop_ID}}
        </div>
        <div class="fieldWrapper">
          <label for="date">방문날짜:</label>
          {{form.themeRevDate}}
        </div>
      </div>
    </div>

    <div class="text-review box">
      <div class="boxTitle text-bottom">텍스트 리뷰</div>
      {{form.themeRevContent}}
    </div>
  </form>
  </div> 

{% endblock content %}
{% block js %}
<script src="{% static 'widgets/rateit/jquery.rateit.min.js' %}" ></script>
<script type="text/javascript" src="/static/js/new_themeRev.js"></script>
{% comment %} <script src="{% static 'widgets/rateit/jquery.rateit.js' %}" ></script> {% endcomment %}
<script>
  $('#star_id_grade').click(function(){
    star = $('#star_id_grade').rateit('value')
    $('#id_grade').text(star)
    $('#id_grade').val(star)
    test = $('#id_grade')
    console.log(test.val())
  });
</script>
{% endblock js %}

BANGAPP/templates/new_themeRevTest.html
{% comment %} 별점 기능 에러 대응을 위한 테스트페이지(실이용x) {% endcomment %}

<!--starWidget없이 직접 input 불러오는 하는 방식(성공)-->
{% comment %} {% extends './base.html' %}
{% load static %}
{% block css %}
  <link rel="stylesheet" href="{% static 'widgets/rateit/rateit.css' %}">
  <style>
    .content{margin-top: 20vh; margin-left:10vw;}
  </style>
{% endblock css %}

{% block content %}
<div class="rateit" data-rateit-value="5" data-rateit-ispreset="true" 
data-rateit-readonly="true" data-rateit-mode="font"  style="font-size:3vw">
</div>

<div class="content">
  <form action="" method="post">
    {% csrf_token %}
  <input type="range" name="grade" value="5" required="" id="id_grade" min="0" max="5" step="1" style="display:none;">
  <div id="star_id_grade" class="rateit rateit-bg" data-rateit-backingfld="#id_grade" data-rateit-mode="font"  style="font-size:50px">
  </div> <br>test
  {{form.con}}<br>
  {{form.Date}}<br>
  {{form.theme_ID2}}<br>
  {{form.shop_ID2}}<br>

  <button type="submit"></button>
  </form>
</div>
  {% endblock content %}

{% block js %}
  <script src="{% static 'widgets/rateit/jquery.rateit.min.js' %}" ></script>
  <script src="{% static 'widgets/rateit/jquery.rateit.js' %}" ></script>
  <script type="text/javascript" src="/static/js/new_themeRev.js"></script>

  <script>
    $('#star_id_grade').click(function(){
      star = $('#star_id_grade').rateit('value')
      $('#id_grade').text(star)
      $('#id_grade').val(star)
      test = $('#id_grade')
      console.log(test.val())
    });
    
  </script>   
{% endblock js %} {% endcomment %}




<!--별점 위젯 불러오고 form 필드로 post하는 방식 (실패)-->
{% comment %} 
{% include "widgets/star_rate.html" %}

<form action="" method="post">
  {% csrf_token %}
  {% for field in form %}
  <div class="form-group">
    {{field}}
  </div>
  {% if field.errors %}
  <span style="colro: red">{{ form.errors }} </span>
  {% endif %}

  {% endfor %}
  <button type="submit" class="btn btn-primary"></button>
</form> 

<script type="text/javascript" src="/static/widgets/rateit/jquery.rateit.js"></script> {% endcomment %}

BANGAPP/templates/warning.html
{% extends './base.html' %}
{% load static %}
{% block css %}
<style>
  .content{
    margin-top: 50vh;
    margin-left: 30vw;
  }
</style>
{% endblock css %}
{% block content %}
<div class="content">
잘못된 경로로 접근 하셨습니다.<br>
<a href="{% url 'login' %}">
로그인페이지로 돌아가기
</a><br>
<a href="{% url 'home' %}">
  홈화면으로 돌아가기
</a>
</content>
{% endblock content %}